# Generated by Django 4.1.12 on 2023-10-23 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('contraseña', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('role', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor')], max_length=10)),
            ],
        ),
    ]
